const OILS = [
  // ============ CITRUS / FRUIT (true EOs) ============
  {
    id: "sweet-orange", name: "Sweet Orange", latin: "Citrus sinensis",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Bright", "Juicy", "Fresh"],
    constituents: [{c:"Limonene", pct:90}, {c:"Myrcene", pct:2}, {c:"α-Pinene", pct:0.5}],
    phototoxic: false, phototox_note: "Non-phototoxic (expressed peel oil, but limonene-dominant with negligible bergapten).",
    max_dermal: 100, // % non-hazard
    cautions: ["Oxidizes quickly — store cool, use within 12 months to avoid skin sensitization."],
    pregnancy: "Generally safe",
    pairs_with: ["Bergamot","Lavender","Frankincense","Cinnamon","Vanilla","Ylang Ylang","Clove"],
    uses: ["Mood lift","Diffusion","Kitchen deodorizer"]
  },
  {
    id: "lemon", name: "Lemon", latin: "Citrus limon",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sharp","Zesty","Clean","Bright"],
    constituents: [{c:"Limonene", pct:65}, {c:"β-Pinene", pct:12}, {c:"γ-Terpinene", pct:9}, {c:"Citral", pct:2}],
    phototoxic: true, phototox_note: "PHOTOTOXIC. Max 2.0% on skin exposed to UV within 12h (IFRA).",
    max_dermal: 2.0,
    cautions: ["Do not apply before sun exposure or tanning beds.","Oxidizes — refrigerate."],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender","Rosemary","Eucalyptus","Peppermint","Tea Tree","Frankincense"],
    uses: ["Concentration","Air purifier","Cleaning"]
  },
  {
    id: "bergamot", name: "Bergamot", latin: "Citrus bergamia",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Sweet","Floral","Citrus","Slightly spicy"],
    constituents: [{c:"Limonene", pct:38}, {c:"Linalyl acetate", pct:28}, {c:"Linalool", pct:12}, {c:"γ-Terpinene", pct:7}],
    phototoxic: true, phototox_note: "STRONGLY PHOTOTOXIC (bergapten). Max 0.4% on sun-exposed skin. Bergapten-free (FCF) versions are safe.",
    max_dermal: 0.4,
    cautions: ["The most phototoxic common oil. Use FCF/bergapten-free for skin blends.","Do not use before UV exposure."],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender","Neroli","Frankincense","Ylang Ylang","Sandalwood","Jasmine"],
    uses: ["Anxiety","Perfumery","Earl Grey signature"]
  },
  {
    id: "grapefruit", name: "Grapefruit", latin: "Citrus paradisi",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Bright","Tart","Sparkling","Slightly bitter"],
    constituents: [{c:"Limonene", pct:92}, {c:"Myrcene", pct:2}, {c:"Nootkatone", pct:0.5}],
    phototoxic: true, phototox_note: "Mildly phototoxic. Max 4.0% on sun-exposed skin.",
    max_dermal: 4.0,
    cautions: ["Oxidizes rapidly."],
    pregnancy: "Generally safe",
    pairs_with: ["Rosemary","Peppermint","Frankincense","Lavender","Ylang Ylang"],
    uses: ["Appetite regulation","Energy","Cellulite blends"]
  },
  {
    id: "coconut", name: "Coconut", latin: "Cocos nucifera (fragrance)",
    category: "Fruit", note: "Base", type: "fragrance",
    intensity: 3, blend_strength: 3,
    aroma: ["Creamy","Sweet","Tropical","Nutty"],
    constituents: [], phototoxic: false, phototox_note: "N/A — synthetic accord.",
    cautions: ["Fragrance oil, not a true essential oil — no therapeutic effect."],
    pregnancy: "Topical use only",
    pairs_with: ["Vanilla","Sweet Orange","Lime","Ylang Ylang","Sandalwood"],
    uses: ["Perfumery","Candle-making"]
  },
  {
    id: "passionfruit", name: "Passionfruit", latin: "Passiflora edulis (fragrance)",
    category: "Fruit", note: "Top", type: "fragrance",
    intensity: 3, blend_strength: 3,
    aroma: ["Tropical","Tangy","Sweet","Exotic"],
    constituents: [], phototoxic: false, phototox_note: "N/A — synthetic accord.",
    cautions: ["Fragrance oil, not a true essential oil."],
    pregnancy: "Topical use only",
    pairs_with: ["Coconut","Vanilla","Ylang Ylang","Grapefruit","Mango"],
    uses: ["Summer diffusion","Perfumery"]
  },
  { id:"blueberry", name:"Blueberry", latin:"Vaccinium sect. (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Sweet","Juicy","Tart","Berry"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Vanilla","Sweet Orange","Lavender","Mint"], uses:["Diffusion","Candles"] },
  { id:"grape", name:"Grape", latin:"Vitis vinifera (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Sweet","Wine-like","Fruity"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Vanilla","Blackcurrant","Rose"], uses:["Perfumery"] },
  { id:"raspberry", name:"Raspberry", latin:"Rubus idaeus (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Sweet","Tart","Berry","Juicy"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Vanilla","Chocolate","Rose","Sweet Orange"], uses:["Gourmand perfumery"] },
  { id:"hami-melon", name:"Hami Melon", latin:"Cucumis melo (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Fresh","Sweet","Watery","Melon"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cucumber","Watermelon","Green Tea"], uses:["Aquatic perfumery"] },
  { id:"watermelon", name:"Watermelon", latin:"Citrullus lanatus (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Watery","Sweet","Fresh","Green"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cucumber","Mint","Lime"], uses:["Summer diffusion"] },
  { id:"cherry", name:"Cherry", latin:"Prunus avium (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Sweet","Almond-like","Fruity","Rich"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Vanilla","Almond","Chocolate","Rose"], uses:["Gourmand perfumery"] },
  { id:"cranberry", name:"Cranberry", latin:"Vaccinium macrocarpon (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Tart","Bright","Berry"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cinnamon","Vanilla","Orange"], uses:["Holiday diffusion"] },
  { id:"banana", name:"Banana", latin:"Musa (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Creamy","Tropical","Sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Coconut","Vanilla","Rum"], uses:["Gourmand"] },
  { id:"mango", name:"Mango", latin:"Mangifera indica (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Tropical","Juicy","Sweet","Sunny"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Coconut","Passionfruit","Ylang Ylang"], uses:["Tropical perfumery"] },
  { id:"cucumber", name:"Cucumber", latin:"Cucumis sativus (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:1, blend_strength:1, aroma:["Fresh","Green","Watery","Clean"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Melon","Mint","Green Tea"], uses:["Spa diffusion"] },
  { id:"peach", name:"Peach", latin:"Prunus persica (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Velvety","Sweet","Fuzzy","Fruity"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Rose","Vanilla","Osmanthus"], uses:["Feminine perfumery"] },
  { id:"guava", name:"Guava", latin:"Psidium guajava (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Tropical","Musky-sweet","Pink"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Passionfruit","Rose","Coconut"], uses:["Perfumery"] },
  { id:"pineapple", name:"Pineapple", latin:"Ananas comosus (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Tropical","Tart","Sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Coconut","Rum","Sweet Orange"], uses:["Tropical accord"] },
  { id:"fig", name:"Fig", latin:"Ficus carica (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Green","Milky","Sweet","Woody"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Sandalwood","Vanilla","Coconut"], uses:["Sophisticated perfumery"] },
  { id:"strawberry", name:"Strawberry", latin:"Fragaria (fragrance)", category:"Fruit", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Sweet","Bright","Berry","Sunny"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Vanilla","Chocolate","Cream"], uses:["Gourmand"] },
  { id:"apple", name:"Apple", latin:"Malus domestica (fragrance)", category:"Fruit", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Crisp","Fresh","Sweet","Green"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cinnamon","Vanilla","Clove"], uses:["Autumn diffusion"] },

  // ============ PLANT / HERB / LEAF (mostly true EOs) ============
  {
    id: "peppermint", name: "Peppermint", latin: "Mentha × piperita",
    category: "Herb", note: "Top", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Sharp","Cool","Menthol","Green"],
    constituents: [{c:"Menthol", pct:42}, {c:"Menthone", pct:23}, {c:"1,8-Cineole", pct:6}, {c:"Menthyl acetate", pct:5}, {c:"Pulegone", pct:1}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 5.4,
    cautions: ["Avoid in children under 6 (menthol — risk of laryngospasm).","Avoid near face of infants.","Not for pregnancy/nursing.","Can antagonize homeopathic remedies."],
    pregnancy: "AVOID",
    pairs_with: ["Eucalyptus","Rosemary","Lavender","Lemon","Grapefruit"],
    uses: ["Headache relief","Focus","Digestive support","Cooling"]
  },
  {
    id: "eucalyptus", name: "Eucalyptus", latin: "Eucalyptus globulus",
    category: "Herb", note: "Top", type: "essential",
    intensity: 5, blend_strength: 4,
    aroma: ["Camphoraceous","Fresh","Medicinal","Woody"],
    constituents: [{c:"1,8-Cineole (Eucalyptol)", pct:70}, {c:"α-Pinene", pct:10}, {c:"Limonene", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 20,
    cautions: ["DO NOT use on/near face of children under 10 (1,8-cineole — CNS depression risk).","Asthmatics: introduce cautiously."],
    pregnancy: "Use with caution",
    pairs_with: ["Peppermint","Rosemary","Tea Tree","Lavender","Lemon","Pine"],
    uses: ["Respiratory","Decongestant","Air purification"]
  },
  {
    id: "verbena", name: "Verbena (Lemon)", latin: "Aloysia citriodora",
    category: "Herb", note: "Top", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Bright","Lemony","Herbaceous","Fresh"],
    constituents: [{c:"Citral (Geranial+Neral)", pct:35}, {c:"Limonene", pct:20}, {c:"Geraniol", pct:5}],
    phototoxic: true, phototox_note: "Mildly phototoxic. Max 0.9% on sun-exposed skin.",
    max_dermal: 0.9,
    cautions: ["High citral — skin sensitization risk.","IFRA restricted."],
    pregnancy: "Avoid",
    pairs_with: ["Lavender","Neroli","Bergamot","Geranium"],
    uses: ["Uplifting perfumery"]
  },
  {
    id: "thyme", name: "Thyme", latin: "Thymus vulgaris (linalool ct)",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 5, blend_strength: 4,
    aroma: ["Herbal","Warm","Green","Medicinal"],
    constituents: [{c:"Linalool", pct:70}, {c:"Linalyl acetate", pct:8}, {c:"Thymol", pct:3}],
    phototoxic: false, phototox_note: "Non-phototoxic (linalool ct); thymol/carvacrol chemotypes are dermal irritants.",
    max_dermal: 1.3,
    cautions: ["Chemotype matters — thymol/carvacrol types are hot on skin.","Avoid in high blood pressure."],
    pregnancy: "Avoid",
    pairs_with: ["Rosemary","Lemon","Bergamot","Lavender","Tea Tree"],
    uses: ["Antimicrobial","Respiratory"]
  },
  {
    id: "clary-sage", name: "Clary Sage", latin: "Salvia sclarea",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Herbal","Sweet","Nutty","Musky-floral"],
    constituents: [{c:"Linalyl acetate", pct:62}, {c:"Linalool", pct:15}, {c:"Germacrene D", pct:5}, {c:"Sclareol", pct:2}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Avoid with alcohol (potentiation reported).","Traditionally avoided in early pregnancy — safe in labor per some references."],
    pregnancy: "Avoid until labor",
    pairs_with: ["Lavender","Bergamot","Geranium","Sandalwood","Ylang Ylang"],
    uses: ["Hormonal balance","Anxiety","Labor support"]
  },
  {
    id: "tea-tree", name: "Tea Tree", latin: "Melaleuca alternifolia",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 3,
    aroma: ["Medicinal","Fresh","Camphoraceous","Sharp"],
    constituents: [{c:"Terpinen-4-ol", pct:40}, {c:"γ-Terpinene", pct:20}, {c:"α-Terpinene", pct:10}, {c:"1,8-Cineole", pct:3}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 15,
    cautions: ["Oxidizes to sensitizing compounds — use within 12 months.","Toxic to cats."],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender","Eucalyptus","Lemon","Rosemary","Peppermint"],
    uses: ["Antimicrobial","Skin care","Blemishes"]
  },
  {
    id: "cedarwood", name: "Cedarwood (Atlas)", latin: "Cedrus atlantica",
    category: "Wood", note: "Base", type: "essential",
    intensity: 4, blend_strength: 5,
    aroma: ["Woody","Dry","Sweet","Balsamic"],
    constituents: [{c:"β-Himachalene", pct:40}, {c:"α-Himachalene", pct:15}, {c:"Atlantone", pct:8}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Avoid in pregnancy (some references)."],
    pregnancy: "Avoid",
    pairs_with: ["Bergamot","Sandalwood","Rose","Ylang Ylang","Frankincense"],
    uses: ["Grounding","Sleep","Insect repellent"]
  },
  {
    id: "lemongrass", name: "Lemongrass", latin: "Cymbopogon flexuosus",
    category: "Herb", note: "Top", type: "essential",
    intensity: 5, blend_strength: 4,
    aroma: ["Sharp","Lemony","Grassy","Bright"],
    constituents: [{c:"Citral (Geranial+Neral)", pct:75}, {c:"Geraniol", pct:5}, {c:"Myrcene", pct:5}],
    phototoxic: false, phototox_note: "Not phototoxic per Tisserand, but high citral = sensitizer.",
    max_dermal: 0.7,
    cautions: ["Strong dermal sensitizer — dilute heavily.","Contraindicated in glaucoma, prostatic hyperplasia."],
    pregnancy: "Avoid",
    pairs_with: ["Basil","Cedarwood","Geranium","Lavender","Tea Tree"],
    uses: ["Insect repellent","Muscle aches"]
  },
  {
    id: "rosemary", name: "Rosemary", latin: "Rosmarinus officinalis (1,8-cineole ct)",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Herbal","Camphoraceous","Woody","Fresh"],
    constituents: [{c:"1,8-Cineole", pct:45}, {c:"α-Pinene", pct:12}, {c:"Camphor", pct:11}, {c:"β-Pinene", pct:8}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 16.5,
    cautions: ["Avoid with epilepsy (camphor).","Avoid on children under 10 (1,8-cineole)."],
    pregnancy: "Avoid",
    pairs_with: ["Peppermint","Lemon","Eucalyptus","Basil","Frankincense"],
    uses: ["Memory","Hair","Circulation"]
  },
  {
    id: "cypress", name: "Cypress", latin: "Cupressus sempervirens",
    category: "Wood", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Woody","Fresh","Coniferous","Dry"],
    constituents: [{c:"α-Pinene", pct:50}, {c:"δ-3-Carene", pct:20}, {c:"Cedrol", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Oxidized α-pinene is sensitizing — store cool."],
    pregnancy: "Use with caution",
    pairs_with: ["Bergamot","Juniper","Lavender","Pine","Sandalwood"],
    uses: ["Circulation","Grief","Varicose"]
  },
  {
    id: "spearmint", name: "Spearmint", latin: "Mentha spicata",
    category: "Herb", note: "Top", type: "essential",
    intensity: 4, blend_strength: 3,
    aroma: ["Sweet","Minty","Green","Softer than peppermint"],
    constituents: [{c:"(R)-(-)-Carvone", pct:60}, {c:"Limonene", pct:15}, {c:"1,8-Cineole", pct:3}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 1.7,
    cautions: ["Gentler than peppermint — safer for children over 2.","Avoid in G6PD deficiency."],
    pregnancy: "Use with caution",
    pairs_with: ["Lavender","Eucalyptus","Rosemary","Basil","Grapefruit"],
    uses: ["Digestion","Cooling","Child-friendly mint"]
  },
  {
    id: "vanilla", name: "Vanilla", latin: "Vanilla planifolia (CO2/absolute)",
    category: "Food", note: "Base", type: "essential",
    intensity: 4, blend_strength: 5,
    aroma: ["Sweet","Warm","Balsamic","Creamy"],
    constituents: [{c:"Vanillin", pct:85}, {c:"4-Hydroxybenzaldehyde", pct:9}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["True vanilla is an absolute/CO2 — very viscous, needs warming."],
    pregnancy: "Generally safe",
    pairs_with: ["Sandalwood","Ylang Ylang","Rose","Sweet Orange","Cinnamon","Bergamot"],
    uses: ["Comfort","Sleep","Perfumery"]
  },
  {
    id: "vetiver", name: "Vetiver", latin: "Vetiveria zizanioides",
    category: "Root", note: "Base", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Earthy","Smoky","Damp","Rooty"],
    constituents: [{c:"Khusimol", pct:15}, {c:"α-Vetivone", pct:5}, {c:"β-Vetivone", pct:5}, {c:"Vetiverol", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Very viscous — warm dropper."],
    pregnancy: "Use with caution",
    pairs_with: ["Sandalwood","Rose","Ylang Ylang","Bergamot","Lavender"],
    uses: ["Grounding","Sleep","ADHD focus"]
  },
  {
    id: "mugwort", name: "Mugwort", latin: "Artemisia vulgaris",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Herbal","Camphoraceous","Bitter","Sage-like"],
    constituents: [{c:"α-Thujone", pct:12}, {c:"β-Thujone", pct:15}, {c:"Camphor", pct:15}, {c:"1,8-Cineole", pct:10}],
    phototoxic: false, phototox_note: "Non-phototoxic but neurotoxic.",
    max_dermal: 0.1,
    cautions: ["HIGH THUJONE — neurotoxic. NOT for aromatherapy per Tisserand.","Avoid entirely if pregnant, epileptic, or with children."],
    pregnancy: "AVOID — abortifacient",
    pairs_with: ["Cedarwood","Sage"],
    uses: ["Ritual only — not recommended for topical/inhalation therapy"]
  },
  {
    id: "fir", name: "Fir", latin: "Abies balsamea",
    category: "Wood", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Coniferous","Fresh","Woody","Balsamic"],
    constituents: [{c:"β-Pinene", pct:30}, {c:"δ-3-Carene", pct:20}, {c:"α-Pinene", pct:15}, {c:"Bornyl acetate", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Oxidized pinenes sensitize — store cool."],
    pregnancy: "Generally safe",
    pairs_with: ["Cypress","Cedarwood","Lemon","Rosemary","Eucalyptus"],
    uses: ["Respiratory","Forest bathing","Holiday scents"]
  },

  // ============ FLORALS (mixed) ============
  { id:"freesia", name:"Freesia", latin:"Freesia (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Floral","Fresh","Sweet","Peppery"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Rose","Peach","Jasmine"], uses:["Perfumery"] },
  {
    id: "rose", name: "Rose (Otto)", latin: "Rosa × damascena",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Rich","Floral","Sweet","Honeyed"],
    constituents: [{c:"Citronellol", pct:32}, {c:"Geraniol", pct:18}, {c:"Nerol", pct:8}, {c:"Phenylethanol", pct:2}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Extremely expensive — often adulterated."],
    pregnancy: "Use after 1st trimester",
    pairs_with: ["Sandalwood","Bergamot","Geranium","Jasmine","Vanilla","Frankincense"],
    uses: ["Heart","Skincare","Emotional healing"]
  },
  { id:"white-tea", name:"White Tea", latin:"Camellia sinensis (fragrance)", category:"Floral", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Delicate","Fresh","Green","Powdery"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cucumber","Jasmine","Bergamot"], uses:["Spa"] },
  {
    id: "orange-blossom", name: "Orange Blossom (Neroli)", latin: "Citrus aurantium (flower)",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 5,
    aroma: ["Floral","Sweet","Green","Honeyed"],
    constituents: [{c:"Linalool", pct:45}, {c:"Limonene", pct:12}, {c:"β-Pinene", pct:10}, {c:"Linalyl acetate", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic (unlike Petitgrain leaf oil, which contains no bergapten either).",
    max_dermal: 100,
    cautions: ["Very expensive — verify authenticity."],
    pregnancy: "Generally safe",
    pairs_with: ["Bergamot","Rose","Jasmine","Sandalwood","Ylang Ylang"],
    uses: ["Anxiety","Depression","Skincare","Bridal perfumery"]
  },
  {
    id: "geranium", name: "Geranium", latin: "Pelargonium graveolens",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Floral","Rosy","Green","Slightly minty"],
    constituents: [{c:"Citronellol", pct:30}, {c:"Geraniol", pct:15}, {c:"Linalool", pct:9}, {c:"Isomenthone", pct:6}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 17.5,
    cautions: ["Mild sensitizer — patch test."],
    pregnancy: "Use with caution",
    pairs_with: ["Rose","Lavender","Bergamot","Clary Sage","Sandalwood"],
    uses: ["Hormonal balance","Rose substitute","Skincare"]
  },
  { id:"osmanthus", name:"Osmanthus", latin:"Osmanthus fragrans (absolute)", category:"Floral", note:"Middle", type:"essential",
    intensity:4, blend_strength:5, aroma:["Apricot","Leather","Peachy","Sweet-floral"],
    constituents:[{c:"β-Ionone", pct:12},{c:"γ-Decalactone", pct:4},{c:"Dihydro-β-ionone", pct:3}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:100,
    cautions:["Absolute — solvent residues possible."], pregnancy:"Use with caution",
    pairs_with:["Peach","Rose","Sandalwood","Bergamot"], uses:["Fine perfumery","Tea"] },
  { id:"sakura", name:"Sakura (Cherry Blossom)", latin:"Prunus serrulata (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Delicate","Powdery","Floral","Sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["No true EO exists commercially — always fragrance."], pregnancy:"Topical",
    pairs_with:["Rose","Peach","Vanilla"], uses:["Spring perfumery"] },
  {
    id: "jasmine", name: "Jasmine (Absolute)", latin: "Jasminum grandiflorum",
    category: "Floral", note: "Base", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Intensely floral","Sweet","Narcotic","Fruity"],
    constituents: [{c:"Benzyl acetate", pct:24}, {c:"Benzyl benzoate", pct:14}, {c:"Phytol", pct:11}, {c:"Linalool", pct:6}, {c:"Indole", pct:2}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.7,
    cautions: ["Indole can smell fecal at high concentration — use tiny amounts."],
    pregnancy: "Use only during labor",
    pairs_with: ["Rose","Sandalwood","Bergamot","Ylang Ylang","Vanilla"],
    uses: ["Aphrodisiac","Depression","Labor"]
  },
  {
    id: "ylang-ylang", name: "Ylang Ylang", latin: "Cananga odorata",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Intensely floral","Sweet","Creamy","Exotic"],
    constituents: [{c:"Germacrene D", pct:20}, {c:"Linalool", pct:14}, {c:"Benzyl acetate", pct:10}, {c:"Benzyl benzoate", pct:6}, {c:"Geranyl acetate", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.8,
    cautions: ["Can cause headaches in some people at high concentration.","Sensitization risk — patch test."],
    pregnancy: "Use with caution",
    pairs_with: ["Bergamot","Sandalwood","Jasmine","Rose","Grapefruit","Vetiver"],
    uses: ["Aphrodisiac","Blood pressure","Hair"]
  },
  { id:"lily", name:"Lily", latin:"Lilium (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:4, blend_strength:4, aroma:["Rich","Heady","Green-floral","Sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["No commercial EO — always fragrance."], pregnancy:"Topical",
    pairs_with:["Rose","Jasmine","White Tea"], uses:["Perfumery"] },
  { id:"gardenia", name:"Gardenia", latin:"Gardenia jasminoides (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:4, blend_strength:4, aroma:["Creamy","Tropical-floral","Rich"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Almost always fragrance — true absolute is very rare."], pregnancy:"Topical",
    pairs_with:["Jasmine","Tuberose","Coconut"], uses:["Tropical perfumery"] },
  {
    id: "chamomile", name: "Chamomile (Roman)", latin: "Chamaemelum nobile",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Sweet","Apple-like","Herbal","Warm"],
    constituents: [{c:"Isobutyl angelate", pct:37}, {c:"Isoamyl angelate", pct:22}, {c:"Methylallyl angelate", pct:9}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Ragweed allergy — patch test.","German chamomile (Matricaria) has different chemistry (chamazulene)."],
    pregnancy: "Use with caution",
    pairs_with: ["Lavender","Rose","Bergamot","Geranium","Ylang Ylang"],
    uses: ["Sleep","Anxiety","Children (dilute)"]
  },
  {
    id: "clove", name: "Clove Bud", latin: "Syzygium aromaticum",
    category: "Spice", note: "Base", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Spicy","Warm","Sweet","Medicinal"],
    constituents: [{c:"Eugenol", pct:80}, {c:"β-Caryophyllene", pct:10}, {c:"Eugenyl acetate", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.5,
    cautions: ["Strong dermal sensitizer and mucous membrane irritant.","Anticoagulant — avoid with blood thinners.","Never neat on skin — clove is a leading cause of EO-related dermatitis."],
    pregnancy: "Avoid",
    pairs_with: ["Cinnamon","Orange","Vanilla","Ylang Ylang","Frankincense"],
    uses: ["Toothache (dilute)","Winter blends","Antimicrobial"]
  },
  {
    id: "lavender", name: "Lavender", latin: "Lavandula angustifolia",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 4,
    aroma: ["Floral","Herbal","Sweet","Fresh"],
    constituents: [{c:"Linalyl acetate", pct:38}, {c:"Linalool", pct:32}, {c:"β-Caryophyllene", pct:4}, {c:"Lavandulol", pct:1}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Debated prepubertal gynecomastia link (Ramsey et al. 2019) — evidence weak.","Very safe overall."],
    pregnancy: "Generally safe",
    pairs_with: ["Bergamot","Rosemary","Cedarwood","Tea Tree","Peppermint","Rose","Chamomile"],
    uses: ["Sleep","Anxiety","Skin (burns, cuts)","All-purpose"]
  },
  { id:"plum-blossom", name:"Plum Blossom", latin:"Prunus mume (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Sweet","Fruity-floral","Delicate"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Sakura","Rose","White Tea"], uses:["Asian perfumery"] },
  { id:"lotus", name:"Lotus", latin:"Nelumbo nucifera (absolute or fragrance)", category:"Floral", note:"Base", type:"essential",
    intensity:4, blend_strength:5, aroma:["Watery-floral","Sweet","Meditative","Powdery"],
    constituents:[{c:"1,4-Dimethoxybenzene", pct:20},{c:"Palmitic acid", pct:8},{c:"Linoleic acid", pct:6}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:2,
    cautions:["Often adulterated — verify supplier.","Absolute uses solvent extraction."], pregnancy:"Use with caution",
    pairs_with:["Sandalwood","Rose","Jasmine"], uses:["Meditation","Fine perfumery"] },
  { id:"orchid", name:"Orchid", latin:"Orchidaceae (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:4, aroma:["Exotic","Vanillic","Floral","Soft"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["No true EO — always fragrance."], pregnancy:"Topical",
    pairs_with:["Vanilla","Sandalwood","Jasmine"], uses:["Perfumery"] },
  {
    id: "marjoram", name: "Marjoram (Sweet)", latin: "Origanum majorana",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 3,
    aroma: ["Herbal","Warm","Woody","Slightly camphoraceous"],
    constituents: [{c:"Terpinen-4-ol", pct:26}, {c:"γ-Terpinene", pct:14}, {c:"α-Terpinene", pct:8}, {c:"Sabinene", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Hypotensive — caution with low BP."],
    pregnancy: "Avoid",
    pairs_with: ["Lavender","Bergamot","Chamomile","Cedarwood","Rosemary"],
    uses: ["Sleep","Muscle relaxant","Grief"]
  },
  { id:"sweet-tobacco", name:"Sweet Tobacco", latin:"Nicotiana (absolute/fragrance)", category:"Leather", note:"Base", type:"fragrance",
    intensity:4, blend_strength:5, aroma:["Sweet","Smoky","Hay-like","Rich"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Typically fragrance oil; true absolute is uncommon."], pregnancy:"Topical",
    pairs_with:["Vanilla","Leather","Sandalwood","Rum"], uses:["Masculine perfumery"] },
  { id:"lily-of-valley", name:"Lily of the Valley", latin:"Convallaria majalis (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Green-floral","Fresh","Sweet","Delicate"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["NO natural EO exists — always synthetic (muguet)."], pregnancy:"Topical",
    pairs_with:["Rose","Jasmine","White Tea"], uses:["Feminine perfumery"] },
  { id:"violet", name:"Violet", latin:"Viola odorata (fragrance/absolute)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Powdery","Sweet","Green-floral"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Leaf absolute exists but retail versions are usually fragrance."], pregnancy:"Topical",
    pairs_with:["Rose","Jasmine","Vanilla"], uses:["Powdery perfumery"] },
  { id:"lemon-balm", name:"Lemon Balm (Melissa)", latin:"Melissa officinalis", category:"Herb", note:"Middle", type:"essential",
    intensity:4, blend_strength:4, aroma:["Lemony","Herbal","Sweet","Green"],
    constituents:[{c:"Citral (Geranial+Neral)", pct:50},{c:"β-Caryophyllene", pct:12},{c:"Geraniol", pct:5}],
    phototoxic:false, phototox_note:"Non-phototoxic but citral-rich = sensitizer.", max_dermal:0.9,
    cautions:["High citral — dilute heavily.","Frequently adulterated."], pregnancy:"Avoid",
    pairs_with:["Lavender","Chamomile","Rose","Bergamot"], uses:["Anxiety","Cold sores"] },
  { id:"green-tea", name:"Green Tea", latin:"Camellia sinensis (fragrance)", category:"Floral", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Fresh","Green","Slightly sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance oil."], pregnancy:"Topical",
    pairs_with:["Cucumber","White Tea","Bergamot"], uses:["Spa"] },
  {
    id: "pine", name: "Pine (Scots)", latin: "Pinus sylvestris",
    category: "Wood", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Coniferous","Fresh","Woody","Sharp"],
    constituents: [{c:"α-Pinene", pct:35}, {c:"β-Pinene", pct:25}, {c:"δ-3-Carene", pct:15}, {c:"Limonene", pct:5}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 15,
    cautions: ["OXIDIZATION IS THE MAIN RISK — oxidized pinenes are strong sensitizers. Store cold, use within 12 months.","Avoid Dwarf Pine (Pinus mugo)."],
    pregnancy: "Use with caution",
    pairs_with: ["Eucalyptus","Cedarwood","Fir","Lemon","Rosemary"],
    uses: ["Respiratory","Forest scent","Cleaning"]
  },
  { id:"honeysuckle", name:"Honeysuckle", latin:"Lonicera (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Sweet","Nectar-like","Floral","Green"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["No natural EO — always fragrance."], pregnancy:"Topical",
    pairs_with:["Jasmine","Rose","Vanilla"], uses:["Summer perfumery"] },
  { id:"tulip", name:"Tulip", latin:"Tulipa (fragrance)", category:"Floral", note:"Middle", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Green-floral","Fresh","Powdery"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["No natural EO — always fragrance."], pregnancy:"Topical",
    pairs_with:["Freesia","White Tea","Rose"], uses:["Spring perfumery"] },
  {
    id: "basil", name: "Basil (Linalool)", latin: "Ocimum basilicum",
    category: "Herb", note: "Top", type: "essential",
    intensity: 4, blend_strength: 3,
    aroma: ["Herbal","Sweet","Green","Slightly anise"],
    constituents: [{c:"Linalool", pct:50}, {c:"1,8-Cineole", pct:8}, {c:"Eugenol", pct:5}, {c:"Methyl chavicol", pct:2}],
    phototoxic: false, phototox_note: "Non-phototoxic (linalool ct); methyl chavicol chemotype is hepatotoxic — avoid.",
    max_dermal: 3,
    cautions: ["ALWAYS check chemotype — avoid methyl chavicol (estragole) types."],
    pregnancy: "Avoid",
    pairs_with: ["Bergamot","Lavender","Geranium","Peppermint","Lemon"],
    uses: ["Focus","Fatigue","Digestion"]
  },

  // ============ LEATHER ============
  { id:"leather", name:"Leather", latin:"Accord (fragrance)", category:"Leather", note:"Base", type:"fragrance",
    intensity:5, blend_strength:5, aroma:["Smoky","Animalic","Warm","Dry"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Synthetic accord — birch tar and quinolines historically."], pregnancy:"Topical",
    pairs_with:["Tobacco","Vetiver","Oud","Rose"], uses:["Masculine perfumery","Chypre"] },

  // ============ WOOD ============
  { id:"teak", name:"Teak", latin:"Tectona grandis (fragrance)", category:"Wood", note:"Base", type:"fragrance",
    intensity:4, blend_strength:4, aroma:["Dry","Woody","Warm","Slightly sweet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Sandalwood","Vetiver","Tobacco"], uses:["Woody perfumery"] },
  { id:"agarwood", name:"Agarwood (Oud)", latin:"Aquilaria malaccensis", category:"Wood", note:"Base", type:"essential",
    intensity:5, blend_strength:5, aroma:["Deep","Woody","Animalic","Balsamic","Complex"],
    constituents:[{c:"α-Agarofuran", pct:5},{c:"Jinkoh-eremol", pct:4},{c:"Sesquiterpenes", pct:60}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:100,
    cautions:["Endangered — CITES-restricted. Verify sustainable source.","Extremely expensive; retail versions often adulterated or fragrance."],
    pregnancy:"Use with caution",
    pairs_with:["Rose","Sandalwood","Saffron","Amber"], uses:["Meditation","High perfumery"] },
  { id:"sandalwood", name:"Sandalwood", latin:"Santalum album (or S. spicatum)", category:"Wood", note:"Base", type:"essential",
    intensity:4, blend_strength:5, aroma:["Woody","Creamy","Sweet","Balsamic"],
    constituents:[{c:"α-Santalol", pct:50},{c:"β-Santalol", pct:22},{c:"epi-β-Santalol", pct:4}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:100,
    cautions:["Mysore sandalwood is CITES-restricted; Australian (S. spicatum) is sustainable alternative."],
    pregnancy:"Generally safe",
    pairs_with:["Rose","Jasmine","Bergamot","Ylang Ylang","Vetiver","Vanilla"],
    uses:["Meditation","Skincare","Fixative"] },

  // ============ FOOD ============
  { id:"milk", name:"Milk", latin:"Accord (fragrance)", category:"Food", note:"Base", type:"fragrance",
    intensity:2, blend_strength:3, aroma:["Creamy","Soft","Powdery","Warm"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Vanilla","Sandalwood","Almond"], uses:["Gourmand"] },
  { id:"coffee", name:"Coffee", latin:"Coffea arabica (CO2)", category:"Food", note:"Base", type:"essential",
    intensity:5, blend_strength:5, aroma:["Roasted","Rich","Bitter","Dark"],
    constituents:[{c:"Furfuryl thiol", pct:0.1},{c:"Pyrazines", pct:5},{c:"Furans", pct:15}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:10,
    cautions:["Very strong — use tiny drops.","Retail 'coffee oil' is usually a fragrance accord."],
    pregnancy:"Generally safe",
    pairs_with:["Vanilla","Sandalwood","Cardamom","Chocolate"], uses:["Morning diffusion","Alertness"] },
  { id:"chocolate", name:"Chocolate", latin:"Theobroma cacao (absolute)", category:"Food", note:"Base", type:"essential",
    intensity:4, blend_strength:5, aroma:["Rich","Sweet","Dark","Nutty"],
    constituents:[{c:"Pyrazines", pct:15},{c:"Esters", pct:20},{c:"Furans", pct:5}],
    phototoxic:false, phototox_note:"Non-phototoxic.", max_dermal:100,
    cautions:["Absolute — solvent residues possible.","Toxic to dogs (theobromine)."],
    pregnancy:"Generally safe",
    pairs_with:["Vanilla","Orange","Mint","Rose","Coffee"], uses:["Gourmand perfumery"] },
  { id:"rum", name:"Rum", latin:"Accord (fragrance)", category:"Food", note:"Middle", type:"fragrance",
    intensity:4, blend_strength:4, aroma:["Boozy","Sweet","Caramelized","Warm"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Vanilla","Tobacco","Coconut","Chocolate"], uses:["Masculine gourmand"] },

  // ============ SPICE ============
  {
    id: "myrrh", name: "Myrrh", latin: "Commiphora myrrha",
    category: "Spice", note: "Base", type: "essential",
    intensity: 4, blend_strength: 5,
    aroma: ["Warm","Balsamic","Bitter","Woody"],
    constituents: [{c:"Furanoeudesma-1,3-diene", pct:25}, {c:"Curzerene", pct:15}, {c:"Lindestrene", pct:12}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Emmenagogue — avoid in pregnancy."],
    pregnancy: "AVOID",
    pairs_with: ["Frankincense","Sandalwood","Rose","Cinnamon","Bergamot"],
    uses: ["Meditation","Oral care","Skincare"]
  },
  {
    id: "cinnamon", name: "Cinnamon Bark", latin: "Cinnamomum verum",
    category: "Spice", note: "Base", type: "essential",
    intensity: 5, blend_strength: 5,
    aroma: ["Warm","Sweet","Spicy","Woody"],
    constituents: [{c:"(E)-Cinnamaldehyde", pct:70}, {c:"Eugenol", pct:8}, {c:"Linalool", pct:4}, {c:"β-Caryophyllene", pct:3}],
    phototoxic: false, phototox_note: "Non-phototoxic but severe dermal irritant.",
    max_dermal: 0.07,
    cautions: ["EXTREME DERMAL HAZARD — one of the most sensitizing oils.","NEVER apply to skin above 0.07%.","Avoid with anticoagulants, diabetes medications."],
    pregnancy: "AVOID",
    pairs_with: ["Sweet Orange","Clove","Frankincense","Vanilla","Ylang Ylang"],
    uses: ["Winter diffusion ONLY","Not for topical use"]
  },
  {
    id: "black-pepper", name: "Black Pepper", latin: "Piper nigrum",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 3,
    aroma: ["Spicy","Warm","Woody","Dry"],
    constituents: [{c:"β-Caryophyllene", pct:22}, {c:"Limonene", pct:16}, {c:"Sabinene", pct:15}, {c:"α-Pinene", pct:10}, {c:"β-Pinene", pct:10}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 25,
    cautions: ["Warm sensation on skin — dilute for sensitive skin."],
    pregnancy: "Use with caution",
    pairs_with: ["Frankincense","Rose","Ginger","Sandalwood","Bergamot"],
    uses: ["Muscle aches","Circulation","Craving reduction"]
  },
  {
    id: "nutmeg", name: "Nutmeg", latin: "Myristica fragrans",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 4, blend_strength: 4,
    aroma: ["Warm","Spicy","Sweet","Woody"],
    constituents: [{c:"Sabinene", pct:22}, {c:"α-Pinene", pct:20}, {c:"β-Pinene", pct:15}, {c:"Myristicin", pct:4}, {c:"Elemicin", pct:1}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.8,
    cautions: ["MYRISTICIN is psychoactive/toxic at high doses.","Avoid with MAOIs.","Not for children."],
    pregnancy: "AVOID",
    pairs_with: ["Cinnamon","Clove","Orange","Frankincense","Ylang Ylang"],
    uses: ["Digestion","Muscle pain","Holiday blends"]
  },
  {
    id: "frankincense", name: "Frankincense", latin: "Boswellia carterii",
    category: "Spice", note: "Base", type: "essential",
    intensity: 4, blend_strength: 5,
    aroma: ["Resinous","Woody","Balsamic","Slightly citrus"],
    constituents: [{c:"α-Pinene", pct:40}, {c:"Limonene", pct:12}, {c:"α-Thujene", pct:8}, {c:"Sabinene", pct:5}, {c:"Incensole acetate", pct:3}],
    phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100,
    cautions: ["Oxidizes — store cool.","Boswellia sacra and B. frereana are alternate species."],
    pregnancy: "Generally safe",
    pairs_with: ["Sandalwood","Rose","Myrrh","Bergamot","Lavender","Cedarwood","Ylang Ylang"],
    uses: ["Meditation","Skincare (anti-aging)","Anxiety","Fixative"]
  },

  // ============ PERFUME ============
  { id:"cologne", name:"Cologne", latin:"Accord (fragrance)", category:"Perfume", note:"Top", type:"fragrance",
    intensity:4, blend_strength:3, aroma:["Fresh","Citrus","Aromatic","Clean"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Bergamot","Neroli","Rosemary","Lemon"], uses:["Perfumery"] },

  // ============ NATURE ============
  { id:"sea-wind", name:"Sea Wind", latin:"Accord (fragrance)", category:"Nature", note:"Top", type:"fragrance",
    intensity:3, blend_strength:3, aroma:["Aquatic","Fresh","Salty","Ozonic"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Cucumber","Melon","White Tea"], uses:["Beach diffusion"] },
  { id:"rain", name:"Rain", latin:"Accord (fragrance)", category:"Nature", note:"Top", type:"fragrance",
    intensity:2, blend_strength:2, aroma:["Petrichor","Ozonic","Green","Wet"], constituents:[],
    phototoxic:false, phototox_note:"N/A", cautions:["Fragrance accord."], pregnancy:"Topical",
    pairs_with:["Vetiver","Green Tea","Bamboo"], uses:["Cool weather diffusion"] }
,
  {
    id: "clementine", name: "Clementine", latin: "Citrus clementina",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Crisp", "Fruity"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic risk; Dilute well",
    max_dermal: 100.0,
    cautions: ["Phototoxic risk; Dilute well"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "kaffir-lime-combava", name: "Kaffir Lime (Combava)", latin: "Citrus hystrix",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Intense", "Tart", "Green citrus"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic; highly potent",
    max_dermal: 100.0,
    cautions: ["Phototoxic; highly potent"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Intense diffusion", "Aromatherapy"]
  },
  {
    id: "kumquat", name: "Kumquat", latin: "Citrus japonica",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Rich citrus", "Tart"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe; dilute before use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "lime-cold-pressed", name: "Lime (Cold Pressed)", latin: "Citrus aurantifolia",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Tart", "Sweet", "Fresh"],
    constituents: [], phototoxic: true, phototox_note: "Highly phototoxic; Max dermal 0.7%",
    max_dermal: 0.7,
    cautions: ["Highly phototoxic; Max dermal 0.7%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Tart diffusion", "Aromatherapy"]
  },
  {
    id: "lime-distilled", name: "Lime (Distilled)", latin: "Citrus aurantifolia",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sharp", "Green", "Citrus"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Non-phototoxic (safe for sun)"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sharp diffusion", "Aromatherapy"]
  },
  {
    id: "mandarin", name: "Mandarin", latin: "Citrus reticulata",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Gentle", "Fruity"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally non-phototoxic; mild"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "tangerine", name: "Tangerine", latin: "Citrus reticulata",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Tangy", "Bright"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "yuzu", name: "Yuzu", latin: "Citrus junos",
    category: "Citrus", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Tart", "Complex", "Floral citrus"],
    constituents: [], phototoxic: true, phototox_note: "Mild phototoxic risk",
    max_dermal: 100.0,
    cautions: ["Mild phototoxic risk"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Tart diffusion", "Aromatherapy"]
  },
  {
    id: "blue-lotus-absolute", name: "Blue Lotus (Absolute)", latin: "Nymphaea caerulea",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Intoxicating", "Rich", "Floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Use highly diluted; rare"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Intoxicating diffusion", "Aromatherapy"]
  },
  {
    id: "carnation-absolute", name: "Carnation (Absolute)", latin: "Dianthus caryophyllus",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Spicy", "Floral", "Honeyed"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Skin sensitization risk; low max dermal"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Spicy diffusion", "Aromatherapy"]
  },
  {
    id: "champaca-absolute", name: "Champaca (Absolute)", latin: "Magnolia champaca",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Exotic", "Rich", "Fruity-floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Skin sensitization risk"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Exotic diffusion", "Aromatherapy"]
  },
  {
    id: "frangipani-plumeria", name: "Frangipani / Plumeria", latin: "Plumeria rubra",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Tropical", "Lush"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Use highly diluted"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "rose-geranium", name: "Rose Geranium", latin: "Pelargonium roseum",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Rosy", "Green", "Citrus notes"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Rosy diffusion", "Aromatherapy"]
  },
  {
    id: "helichrysum-immortelle", name: "Helichrysum / Immortelle", latin: "Helichrysum italicum",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Herbaceous", "Honey", "Tea-like"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe; excellent for skincare"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Herbaceous diffusion", "Aromatherapy"]
  },
  {
    id: "jasmine-sambac", name: "Jasmine Sambac", latin: "Jasminum sambac",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Green", "Sweet", "Exotic floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 4.0,
    cautions: ["Max dermal limit 4%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Green diffusion", "Aromatherapy"]
  },
  {
    id: "lavandin", name: "Lavandin", latin: "Lavandula x intermedia",
    category: "Floral", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sharp", "Camphorous", "Floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sharp diffusion", "Aromatherapy"]
  },
  {
    id: "magnolia", name: "Magnolia", latin: "Magnolia grandiflora",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Creamy", "Sweet", "Bright floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Creamy diffusion", "Aromatherapy"]
  },
  {
    id: "mimosa-absolute", name: "Mimosa (Absolute)", latin: "Acacia dealbata",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Powdery", "Sweet", "Woody floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Skin sensitization risk"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Powdery diffusion", "Aromatherapy"]
  },
  {
    id: "rose-damask", name: "Rose Damask", latin: "Rosa damascena",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Deep", "Sweet", "Classic rose"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.6,
    cautions: ["Max dermal limit 0.6%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Deep diffusion", "Aromatherapy"]
  },
  {
    id: "rose-centifolia-absolute", name: "Rose Centifolia (Absolute)", latin: "Rosa centifolia",
    category: "Floral", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Rich", "Sweet", "Honeyed rose"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Skin sensitization risk"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Rich diffusion", "Aromatherapy"]
  },
  {
    id: "tuberose-absolute", name: "Tuberose (Absolute)", latin: "Polianthes tuberosa",
    category: "Floral", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Heavy", "Sweet", "Exotic floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Use highly diluted"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Heavy diffusion", "Aromatherapy"]
  },
  {
    id: "angelica-leaf", name: "Angelica Leaf", latin: "Angelica archangelica",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Green", "Peppery", "Herbaceous"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic risk",
    max_dermal: 100.0,
    cautions: ["Phototoxic risk"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Green diffusion", "Aromatherapy"]
  },
  {
    id: "blue-tansy", name: "Blue Tansy", latin: "Tanacetum annuum",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Fruity", "Herbaceous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe; yields vivid blue color (chamazulene)"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "camphor-white", name: "Camphor (White)", latin: "Cinnamomum camphora",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sharp", "Piercing", "Medicinal"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Avoid in pregnancy/children"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sharp diffusion", "Aromatherapy"]
  },
  {
    id: "catnip", name: "Catnip", latin: "Nepeta cataria",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Minty", "Herbaceous", "Musty"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Minty diffusion", "Aromatherapy"]
  },
  {
    id: "cilantro", name: "Cilantro", latin: "Coriandrum sativum",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Pungent", "Green", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Pungent diffusion", "Aromatherapy"]
  },
  {
    id: "common-sage", name: "Common Sage", latin: "Salvia officinalis",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Strong", "Spicy", "Camphorous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["High thujone; neurotoxic risk. Avoid in pregnancy"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Strong diffusion", "Aromatherapy"]
  },
  {
    id: "davana", name: "Davana", latin: "Artemisia pallens",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Rich", "Fruity", "Boozy", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Rich diffusion", "Aromatherapy"]
  },
  {
    id: "dill-weed", name: "Dill Weed", latin: "Anethum graveolens",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Fresh", "Sweet", "Herbaceous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Fresh diffusion", "Aromatherapy"]
  },
  {
    id: "eucalyptus-radiata", name: "Eucalyptus Radiata", latin: "Eucalyptus radiata",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Crisp", "Clean", "Camphorous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Gentler than Globulus; still caution with kids"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Crisp diffusion", "Aromatherapy"]
  },
  {
    id: "eucalyptus-lemon", name: "Eucalyptus Lemon", latin: "Eucalyptus citriodora",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Lemony", "Fresh", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Lemony diffusion", "Aromatherapy"]
  },
  {
    id: "fennel-sweet", name: "Fennel (Sweet)", latin: "Foeniculum vulgare",
    category: "Herb", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Anise-like", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Avoid in pregnancy; estrogenic"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "hyssop-decumbens", name: "Hyssop (Decumbens)", latin: "Hyssopus officinalis",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Fresh", "Earthy", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Use Decumbens variety; pure hyssop is neurotoxic"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Fresh diffusion", "Aromatherapy"]
  },
  {
    id: "oregano", name: "Oregano", latin: "Origanum vulgare",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Strong", "Spicy", "Camphorous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 1.1,
    cautions: ["Severe skin irritant; max dermal 1.1%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Strong diffusion", "Aromatherapy"]
  },
  {
    id: "parsley-leaf", name: "Parsley Leaf", latin: "Petroselinum crispum",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Green", "Earthy", "Slightly woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Avoid in pregnancy"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Green diffusion", "Aromatherapy"]
  },
  {
    id: "tarragon", name: "Tarragon", latin: "Artemisia dracunculus",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Anise-like", "Spicy", "Green"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.1,
    cautions: ["Contains estragole; max dermal 0.1%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Anise-like diffusion", "Aromatherapy"]
  },
  {
    id: "yarrow-blue", name: "Yarrow (Blue)", latin: "Achillea millefolium",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Herbaceous", "Spicy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["May interact with certain drugs"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "amyris", name: "Amyris", latin: "Amyris balsamifera",
    category: "Woody", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Woody", "Sweet", "Dry"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Woody diffusion", "Aromatherapy"]
  },
  {
    id: "arborvitae", name: "Arborvitae", latin: "Thuja plicata",
    category: "Woody", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Earthy", "Woody", "Warm"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Generally safe"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Earthy diffusion", "Aromatherapy"]
  },
  {
    id: "hinoki", name: "Hinoki", latin: "Chamaecyparis obtusa",
    category: "Woody", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Clean", "Woody", "Citrusy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Clean diffusion", "Aromatherapy"]
  },
  {
    id: "ho-wood", name: "Ho Wood", latin: "Cinnamomum camphora",
    category: "Woody", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Floral", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use (high linalool)"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "juniper-berry", name: "Juniper Berry", latin: "Juniperus communis",
    category: "Woody", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Fresh", "Crisp", "Woody", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Avoid in kidney disease"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Fresh diffusion", "Aromatherapy"]
  },
  {
    id: "kunzea", name: "Kunzea", latin: "Kunzea ambigua",
    category: "Woody", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Clean", "Medicinal", "Spicy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Clean diffusion", "Aromatherapy"]
  },
  {
    id: "palo-santo", name: "Palo Santo", latin: "Bursera graveolens",
    category: "Woody", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Woody", "Citrus", "Mint"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Sustainable sourcing recommended"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "rosewood", name: "Rosewood", latin: "Aniba rosaeodora",
    category: "Woody", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Woody", "Floral"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Endangered species; use Ho Wood instead"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "spruce-black", name: "Spruce (Black)", latin: "Picea mariana",
    category: "Woody", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Fresh", "Crisp", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Fresh diffusion", "Aromatherapy"]
  },
  {
    id: "spruce-blue", name: "Spruce (Blue)", latin: "Picea pungens",
    category: "Woody", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Crisp", "Evergreen", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Crisp diffusion", "Aromatherapy"]
  },
  {
    id: "spruce-hemlock", name: "Spruce (Hemlock)", latin: "Tsuga canadensis",
    category: "Woody", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Fruity", "Balsamic"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "wintergreen", name: "Wintergreen", latin: "Gaultheria procumbens",
    category: "Woody", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Strong", "Sweet", "Minty"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Contains methyl salicylate; hazardous to kids/pets"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Strong diffusion", "Aromatherapy"]
  },
  {
    id: "balsam-of-peru", name: "Balsam of Peru", latin: "Myroxylon pereirae",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Rich", "Vanilla", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.4,
    cautions: ["Skin sensitization; max dermal 0.4%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Rich diffusion", "Aromatherapy"]
  },
  {
    id: "benzoin", name: "Benzoin", latin: "Styrax benzoin",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Warm", "Vanilla-like"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Skin sensitization risk; dilute well"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "copaiba-balsam", name: "Copaiba Balsam", latin: "Copaifera officinalis",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Mild", "Sweet", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Mild diffusion", "Aromatherapy"]
  },
  {
    id: "elemi", name: "Elemi", latin: "Canarium luzonicum",
    category: "Wood", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Citrus", "Peppery", "Balsamic"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Citrus diffusion", "Aromatherapy"]
  },
  {
    id: "galbanum", name: "Galbanum", latin: "Ferula gummosa",
    category: "Wood", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Intensely green", "Earthy", "Piney"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Intensely green diffusion", "Aromatherapy"]
  },
  {
    id: "gurjum-balsam", name: "Gurjum Balsam", latin: "Dipterocarpus turbinatus",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Mild", "Sweet", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Mild diffusion", "Aromatherapy"]
  },
  {
    id: "labdanum-cistus", name: "Labdanum / Cistus", latin: "Cistus ladanifer",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Deep", "Musky", "Amber", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Deep diffusion", "Aromatherapy"]
  },
  {
    id: "opoponax-sweet-myrrh", name: "Opoponax (Sweet Myrrh)", latin: "Commiphora opoponax",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Balsamic", "Spicy"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic risk; max dermal 0.6%",
    max_dermal: 0.6,
    cautions: ["Phototoxic risk; max dermal 0.6%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "allspice-pimento-berry", name: "Allspice / Pimento Berry", latin: "Pimenta dioica",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Warm", "Spicy", "Sweet clove-like"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.3,
    cautions: ["Mucous membrane irritant; max dermal 0.3%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Warm diffusion", "Aromatherapy"]
  },
  {
    id: "anise", name: "Anise", latin: "Pimpinella anisum",
    category: "Spice", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Licorice-like", "Sweet", "Spicy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 2.4,
    cautions: ["Avoid in pregnancy; max dermal 2.4%"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Licorice-like diffusion", "Aromatherapy"]
  },
  {
    id: "star-anise", name: "Star Anise", latin: "Illicium verum",
    category: "Spice", note: "Top", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Strong licorice", "Spicy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 1.7,
    cautions: ["Avoid in pregnancy; max dermal 1.7%"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Strong licorice diffusion", "Aromatherapy"]
  },
  {
    id: "caraway", name: "Caraway", latin: "Carum carvi",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Spicy", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 1.2,
    cautions: ["Max dermal limit 1.2%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "cardamom", name: "Cardamom", latin: "Elettaria cardamomum",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Spicy", "Sweet", "Balsamic"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Spicy diffusion", "Aromatherapy"]
  },
  {
    id: "cassia", name: "Cassia", latin: "Cinnamomum cassia",
    category: "Spice", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Warm", "Spicy", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 0.05,
    cautions: ["Severe irritant; max dermal 0.05%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Warm diffusion", "Aromatherapy"]
  },
  {
    id: "celery-seed", name: "Celery Seed", latin: "Apium graveolens",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Warm", "Spicy", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Warm diffusion", "Aromatherapy"]
  },
  {
    id: "coriander-seed", name: "Coriander Seed", latin: "Coriandrum sativum",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Spicy", "Woody"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "cubeb", name: "Cubeb", latin: "Piper cubeba",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Spicy", "Woody", "Camphorous"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Spicy diffusion", "Aromatherapy"]
  },
  {
    id: "cumin", name: "Cumin", latin: "Cuminum cyminum",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Spicy", "Earthy", "Warm"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic; max dermal 0.4%",
    max_dermal: 0.4,
    cautions: ["Phototoxic; max dermal 0.4%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Spicy diffusion", "Aromatherapy"]
  },
  {
    id: "ginger", name: "Ginger", latin: "Zingiber officinale",
    category: "Spice", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Warm", "Spicy", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["May irritate sensitive skin"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Warm diffusion", "Aromatherapy"]
  },
  {
    id: "pink-pepper", name: "Pink Pepper", latin: "Schinus molle",
    category: "Spice", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Spicy", "Warm"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "angelica-root", name: "Angelica Root", latin: "Angelica archangelica",
    category: "Root", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Earthy", "Musky", "Sweet"],
    constituents: [], phototoxic: true, phototox_note: "Phototoxic; max dermal 0.8%",
    max_dermal: 0.8,
    cautions: ["Phototoxic; max dermal 0.8%"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Earthy diffusion", "Aromatherapy"]
  },
  {
    id: "carrot-seed", name: "Carrot Seed", latin: "Daucus carota",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Earthy", "Woody", "Root-like"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Avoid in pregnancy"],
    pregnancy: "Avoid during pregnancy",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Earthy diffusion", "Aromatherapy"]
  },
  {
    id: "cypriol-nagarmotha", name: "Cypriol / Nagarmotha", latin: "Cyperus scariosus",
    category: "Herb", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Woody", "Earthy", "Spicy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Woody diffusion", "Aromatherapy"]
  },
  {
    id: "palmarosa", name: "Palmarosa", latin: "Cymbopogon martini",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Sweet", "Floral", "Rose-like"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Sweet diffusion", "Aromatherapy"]
  },
  {
    id: "patchouli", name: "Patchouli", latin: "Pogostemon cablin",
    category: "Wood", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Rich", "Earthy", "Woody", "Sweet"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use; improves with age"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Rich diffusion", "Aromatherapy"]
  },
  {
    id: "plai", name: "Plai", latin: "Zingiber cassumunar",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Cooling", "Spicy", "Green"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Cooling diffusion", "Aromatherapy"]
  },
  {
    id: "spikenard-jatamansi", name: "Spikenard / Jatamansi", latin: "Nardostachys jatamansi",
    category: "Herb", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Deep", "Earthy", "Woody", "Musky"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Endangered species; use Vetiver instead"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Deep diffusion", "Aromatherapy"]
  },
  {
    id: "turmeric", name: "Turmeric", latin: "Curcuma longa",
    category: "Herb", note: "Middle", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Warm", "Spicy", "Earthy"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Warm diffusion", "Aromatherapy"]
  },
  {
    id: "valerian", name: "Valerian", latin: "Valeriana officinalis",
    category: "Herb", note: "Base", type: "essential",
    intensity: 3, blend_strength: 3,
    aroma: ["Earthy", "Musky", "Strong"],
    constituents: [], phototoxic: false, phototox_note: "Non-phototoxic.",
    max_dermal: 100.0,
    cautions: ["Safe for general use; sleep aid"],
    pregnancy: "Generally safe",
    pairs_with: ["Lavender", "Bergamot", "Frankincense"],
    uses: ["Earthy diffusion", "Aromatherapy"]
  }
];

if (typeof module !== 'undefined') module.exports = OILS;